# Dockerfile
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1
WORKDIR /app

# Copy Poetry files and install dependencies
COPY pyproject.toml poetry.lock /app/
RUN pip install poetry && poetry config virtualenvs.create false && poetry install

# Copy the Django app
COPY backend/ /app/

# Run migrations and start Django development server
CMD ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
