# Generated by Django 5.1.4 on 2025-01-03 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the tag.",
                        max_length=30,
                        verbose_name="Tag Name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this tag.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="DailyLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date of the learning entry.",
                        verbose_name="Learning Date",
                    ),
                ),
                (
                    "learning_type",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("Django", "Django"),
                            ("Flask", "Flask"),
                            ("Kubernetes", "Kubernetes"),
                            ("Docker", "Docker"),
                            ("Grafana", "Grafana"),
                            ("SQL", "SQL"),
                            ("NoSQL", "NoSQL"),
                            ("React", "React"),
                            ("Angular", "Angular"),
                            ("Vue", "Vue"),
                            ("Testing", "Testing"),
                            ("CI/CD", "CI/CD"),
                            ("DevOps", "DevOps"),
                            ("Cloud", "Cloud"),
                            ("Machine Learning", "Machine Learning"),
                            ("Data Analysis", "Data Analysis"),
                            ("Security", "Security"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        help_text="The topic of the learning entry.",
                        max_length=50,
                        verbose_name="Learning Topic",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A detailed description of what you learned.",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the entry was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the entry was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this learning entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_learnings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags associated with this learning entry.",
                        related_name="daily_learnings",
                        to="learningtracker.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Learning Entry",
                "verbose_name_plural": "Daily Learning Entries",
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="learningtra_user_id_9604cd_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_date"
                    )
                ],
            },
        ),
    ]
